#FROM permet de deffinir l'imgage de base

FROM ubuntu:latest

#Label Author Email

LABEL Author="William" Email="william.giraud@ecole-isitech.fr"

#Label permet de partager d'autre chose comme des description etc etc

#RUN permet de lancer des script/code

RUN apt update

#ADD permet de copier un fichier depuis l'hote, depuis une adresse, vers l'image

#docker build -t identifiant/node:10-alpine .