# Get the base image

FROM ubuntu:latest
ARG DEBIAN_FRONTEND=noninteractive

# Install all packages

RUN apt-get update
RUN apt-get -y upgrade 
RUN apt-get install -y iproute2
RUN apt install -y wget
RUN wget https://downloads.plex.tv/plex-media-server-new/1.25.5.5492-12f6b8c83/debian/plexmediaserver_1.25.5.5492-12f6b8c83_amd64.deb
RUN dpkg -i plexmediaserver_1.19.3.2852-219a9974e_amd64.deb
RUN apt install -y systemctl

#ENTRYPOINT [ "/bin/bash", "-l", "-c" ]

#CMD [ "ls" ]